/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.provalp1s3.view;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import br.com.provalp1s3.dto.ProfissionalDTO;
import br.com.provalp1s3.ctr.ProfissionalCTR;
/**
 *
 * @author aluno
 */
public class ProfissionalVIEW extends javax.swing.JInternalFrame {
    ProfissionalDTO profissionalDTO = new ProfissionalDTO();
    ProfissionalCTR profissionalCTR = new ProfissionalCTR();
    
    int gravar_alterar;
    ResultSet rs;
    DefaultTableModel modeloJtlConsultarProfissional;
    
    public ProfissionalVIEW() {
        initComponents();
        
        this.liberaCampos(false);
        this.liberaBotoes(true, false, false, false, true);
        this.gravar_alterar = 1;
        modeloJtlConsultarProfissional = (DefaultTableModel) this.jtlConsultarProfissional.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputPreco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inputPesquisaNome = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtlConsultarProfissional = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputDescricao = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputExperiencias = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        inputHabilidades = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        inputCursos = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        inputContato = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();

        jLabel2.setText("Nome:");

        jLabel3.setText("Descricao:");

        jLabel4.setText("Preço:");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Profissionais");

        jLabel11.setText("Nome:");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setText("Consulta");

        btnPesquisar.setText("ok");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jtlConsultarProfissional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtlConsultarProfissional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtlConsultarProfissionalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtlConsultarProfissional);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        inputDescricao.setColumns(20);
        inputDescricao.setRows(5);
        jScrollPane1.setViewportView(inputDescricao);

        jLabel13.setText("Expreciencias:");

        inputExperiencias.setColumns(20);
        inputExperiencias.setRows(5);
        jScrollPane3.setViewportView(inputExperiencias);

        jLabel14.setText("Cursos:");

        inputHabilidades.setColumns(20);
        inputHabilidades.setRows(5);
        jScrollPane4.setViewportView(inputHabilidades);

        jLabel15.setText("Habilidades:");

        inputCursos.setColumns(20);
        inputCursos.setRows(5);
        jScrollPane5.setViewportView(inputCursos);

        inputContato.setColumns(20);
        inputContato.setRows(5);
        jScrollPane6.setViewportView(inputContato);

        jLabel16.setText("Contato:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane6))
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addGap(206, 206, 206))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(15, 15, 15)
                            .addComponent(inputPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btnNovo)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(99, 99, 99)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(84, 84, 84)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(inputPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel16))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        this.preencherTabela(this.inputPesquisaNome.getText().toUpperCase());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void jtlConsultarProfissionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtlConsultarProfissionalMouseClicked
        this.preencherCampos(Integer.parseInt(String.valueOf(
            this.jtlConsultarProfissional.getValueAt(this.jtlConsultarProfissional.getSelectedRow(), 0))
        ));
        this.liberaBotoes(false, true, true, true, true);
    }//GEN-LAST:event_jtlConsultarProfissionalMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.liberaCampos(true);
        this.liberaBotoes(false, true, true, false, true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if(this.gravar_alterar == 1){
            this.gravar();
            this.gravar_alterar = 0;
        } else if(this.gravar_alterar == 2){
            this.alterar();
            this.gravar_alterar = 0;
            this.modeloJtlConsultarProfissional.setNumRows(0);
        } else {
            JOptionPane.showMessageDialog(null, "Erro no sistema, tente novamente.");
        }

        this.limpaCampos();
        this.liberaCampos(false);
        this.liberaBotoes(true, false, false, false, true);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limpaCampos();
        this.liberaCampos(false);
        this.modeloJtlConsultarProfissional.setNumRows(0);
        this.liberaBotoes(true, false, false, false, true);
        this.gravar_alterar = 1;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        this.excluir();
        this.limpaCampos();
        this.liberaCampos(false);
        this.liberaBotoes(true, false, false, false, true);
        this.modeloJtlConsultarProfissional.setNumRows(0);
        this.gravar_alterar = 1;
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    
        private void alterar(){
        try {
            profissionalDTO.setNome(this.inputNome.getText());
            profissionalDTO.setContato(this.inputContato.getText());
            profissionalDTO.setCursos(this.inputCursos.getText());
            profissionalDTO.setDescricao(this.inputDescricao.getText());
            profissionalDTO.setExperiencias(this.inputExperiencias.getText());
            profissionalDTO.setHabilidades(this.inputHabilidades.getText());
            profissionalDTO.setPreco(Float.parseFloat(this.inputPreco.getText()));
            
            JOptionPane.showMessageDialog(null, 
                    this.profissionalCTR.alterarProfissional(profissionalDTO));
        } catch(Exception e){
            System.out.println("Erro alterar()"+ e.getMessage());
        }
    }
    
    private void excluir(){
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o cliente?", "Aviso", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, this.profissionalCTR.deletarProfissional(profissionalDTO));
        }
    }
    
    private void preencherTabela(String nome){
        try {
            this.modeloJtlConsultarProfissional.setNumRows(0);
            
            profissionalDTO.setNome(nome);
            rs = profissionalCTR.consultarProfissional(profissionalDTO, 1);
            
            while(rs.next()){
                this.modeloJtlConsultarProfissional.addRow(new Object[] {
                    rs.getString("id_profissional"),
                    rs.getString("nome")
                });
            }
        } catch(Exception e){
            System.out.println("Erro preencherTabela(): " + e.getMessage());
        } finally{
            profissionalCTR.closeDb();
        }
    }
    
    private void preencherCampos(int id_profissional){
        try{
            this.profissionalDTO.setIdProfissional(id_profissional);
            rs = this.profissionalCTR.consultarProfissional(profissionalDTO, 2);
            if(rs.next()){
                this.limpaCampos();
                
                this.inputNome.setText(rs.getString("nome"));
                this.inputContato.setText(rs.getString("contato"));
                this.inputCursos.setText(rs.getString("cursos"));
                this.inputDescricao.setText(rs.getString("descricao"));
                this.inputExperiencias.setText(rs.getString("experiencias"));
                this.inputHabilidades.setText(rs.getString("habilidades"));
                this.inputPreco.setText(rs.getString("preco"));
                
                this.gravar_alterar = 2;
                this.liberaCampos(true);
            }
        } catch(Exception e){
            System.out.println("Erro: " + e.getMessage());
        } finally {
            this.profissionalCTR.closeDb();
        } 
    }
    
    private void gravar(){
        try {
            profissionalDTO.setNome(this.inputNome.getText());
            profissionalDTO.setContato(this.inputContato.getText());
            profissionalDTO.setCursos(this.inputCursos.getText());
            profissionalDTO.setDescricao(this.inputDescricao.getText());
            profissionalDTO.setExperiencias(this.inputExperiencias.getText());
            profissionalDTO.setHabilidades(this.inputHabilidades.getText());
            profissionalDTO.setPreco(Float.parseFloat(this.inputPreco.getText()));
            
            JOptionPane.showMessageDialog(null, profissionalCTR.inserirProfissional(profissionalDTO));
        } catch(Exception e){
            System.out.println("Erro gravar(): " + e.getMessage());
        }
    }

    public void setPosicao(){
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2,(d.height - this.getSize().height) / 2);
    }
    
    private void liberaCampos(boolean a){
        this.inputNome.setEnabled(a);
        this.inputContato.setEnabled(a);
        this.inputCursos.setEnabled(a);
        this.inputDescricao.setEnabled(a);
        this.inputExperiencias.setEnabled(a);
        this.inputHabilidades.setEnabled(a);
        this.inputPreco.setEnabled(a);
        
    }
    
    private void limpaCampos(){
        this.inputNome.setText("");
        this.inputContato.setText("");
        this.inputCursos.setText("");
        this.inputDescricao.setText("");
        this.inputExperiencias.setText("");
        this.inputHabilidades.setText("");
        this.inputPreco.setText("");
        
    }

    private void liberaBotoes(boolean a, boolean b, boolean c, boolean d, boolean e){
        this.btnNovo.setEnabled(a);
        this.btnCancelar.setEnabled(b);
        this.btnExcluir.setEnabled(d);
        this.btnSair.setEnabled(e);
        this.btnSalvar.setEnabled(c);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JToggleButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextArea inputContato;
    private javax.swing.JTextArea inputCursos;
    private javax.swing.JTextArea inputDescricao;
    private javax.swing.JTextArea inputExperiencias;
    private javax.swing.JTextArea inputHabilidades;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputPesquisaNome;
    private javax.swing.JTextField inputPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jtlConsultarProfissional;
    // End of variables declaration//GEN-END:variables
}
