### teste de buscar aluno por ID
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
    "username": "qwe",
    "password": "qwe"
}


### teste de buscar todos os alunos
GET http://localhost:40000/getAllAlunos HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5Mjc5ODkxNCwiZXhwIjoxNjkyNzk5NTE0fQ.WoRPsoFjppU2NyIuRGRLbNcrQ4JVkxHNvJFIah3SGy0

{    
    
}

### teste de buscar aluno por ID
POST http://localhost:40000/getAlunoByID HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5Mjc5OTE1NCwiZXhwIjoxNjkyNzk5NzU0fQ.Ow7tclE01nA3fLvE1ZTffYO8Rq66WOWl7Vk50nNLfC8

{    
    "alunoid": 1
}
